# -*- coding: utf-8 -*-
"""workshop1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tIUURICg9FD5GfMpdEAqe-AmKfGnEWEx
"""

import numpy as np

# 1. Empty array 2x2
empty_2x2 = np.empty((2,2))
print("Empty 2x2:\n", empty_2x2)

import numpy as np

ones_4x2 = np.ones((4,2))
print("\nOnes 4x2:\n", ones_4x2)

import numpy as np
filled_3x3 = np.full((3,3), 7)
print("\nFull 3x3 with 7:\n", filled_3x3)

import numpy as np
sample = np.array([[1,2,3],[4,5,6]])
zeros_like_sample = np.zeros_like(sample)
print("\nZeros_like sample:\n", zeros_like_sample)

ones_like_sample = np.ones_like(sample)
print("\nOnes_like sample:\n", ones_like_sample)

new_list = [1,2,3,4]
arr_from_list = np.array(new_list)
print("\nArray from list:\n", arr_from_list)

"""problem 2"""

import numpy as np

# 1. Array 10 to 49
arr_10_49 = np.arange(10,50)
print("Array 10..49:\n", arr_10_49)

# 2. 3x3 matrix 0..8
mat_3x3_0_8 = np.arange(9).reshape(3,3)
print("\n3x3 0..8:\n", mat_3x3_0_8)

# 3. Identity matrix 3x3
eye_3 = np.eye(3)
print("\nIdentity 3x3:\n", eye_3)

# 4. Random array size 30 + mean
rand30 = np.random.random(30)
print("\nRandom 30 mean:", rand30.mean())

# 5. Random 10x10 + min/max
rand10x10 = np.random.random((10,10))
print("\n10x10 min:", rand10x10.min(), "max:", rand10x10.max())

# 6. Zero array size 10, replace 5th element
zeros_10 = np.zeros(10)
zeros_10[4] = 1
print("\nZeros array w/ 5th element=1:\n", zeros_10)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print("\nReversed array:", arr[::-1])

# 8. 2D array with border=1, inside=0
border = np.ones((5,5), dtype=int)
border[1:-1,1:-1] = 0
print("\nBorder pattern:\n", border)

# 9. 8x8 checkerboard
checker = np.zeros((8,8), dtype=int)
checker[::2, ::2] = 1
checker[1::2, 1::2] = 1
print("\nCheckerboard:\n", checker)

"""problem 3"""

import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#1. Add
print("x + y:\n", x + y)

# 2. Subtract
print("\nx - y:\n", x - y)

# 3. Multiply by integer
print("\nx * 3:\n", x * 3)

# 4. Square elements
print("\nx squared:\n", x**2)

# 5. Dot products
print("\ndot(v, w):", np.dot(v, w))
print("x dot v:", x.dot(v))
print("x dot y:\n", x.dot(y))

# 6. Concatenate x & y (rows), v & w (columns)
print("\nConcatenate x,y along rows:\n", np.concatenate((x,y), axis=0))
concat_vw = np.vstack((v, w)).T
print("\nConcatenate v & w as columns:\n", concat_vw)

# 7. Why x and v cannot concatenate?
try:
    print(np.concatenate((x, v)))
except Exception as e:
    print("\nError concatenating x and v:\n", e)
    print("Reason: x is 2x2, v is 1D length-2. Their shapes do not match on axis 0.")

"""problem 4

"""

import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. A * A^-1 = I
A_inv = np.linalg.inv(A)
print("A inverse:\n", A_inv)
print("\nA * A^-1:\n", A.dot(A_inv))

# 2. AB != BA
AB = A.dot(B)
BA = B.dot(A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("AB == BA? ->", np.array_equal(AB, BA))

# 3. (AB)^T = B^T A^T
lhs = (A.dot(B)).T
rhs = B.T.dot(A.T)
print("\n(AB)^T:\n", lhs)
print("\nB^T A^T:\n", rhs)
print("Equal? ->", np.array_equal(lhs, rhs))

# 4. Solve system using matrix form
M = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

rhs = np.array([-1,-3,9])

solution = np.linalg.solve(M, rhs)
print("\nSolution using solve():\n", solution)

# 5. Solve using inverse
solution_inv = np.linalg.inv(M).dot(rhs)
print("\nSolution using inverse:\n", solution_inv)